trigger:
- huy-test-fe

resources:
- repo: self

pool:
      vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'PushToDockerHub'
        repository: 'huyhuynh008/testfe'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/front-end/Dockerfile'
        tags: |
              $(tag)

- stage: Deploy
  displayName: Deploy to aks
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'datingapp-default'
        command: 'rollout'
        arguments: 'restart deployment/frontend-deployment'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'