trigger:
- huy-test-fe

resources:
- repo: self

pool:
      vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'PushToDockerHub'
        repository: 'huyhuynh008/testfe'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/front-end/Dockerfile'
        tags: |
              $(tag)

- stage: Deploy
  displayName: Deploy to aks
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure for Students(e19c3989-41f4-4ca6-906a-5b60f8793d44)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: | 
          az aks command invoke \
            --resource-group datingapp \
            --name datingapp-project \
            --command "kubectl rollout restart deployment/frontend-deployment"