version: '3.4'

services:
  sqldata:
    ports:
      - 1433:1433
    image: mcr.microsoft.com/mssql/server
    volumes:
      - "datingapp-db:/var/opt/mssql"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Huy01216903436!
  datingapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqldata
    ports:
      - "44371:80"
      - "44372:443"
volumes:   # add this section
  datingapp-db:   